### ISSUE TITLE
"Function is_flask_request() in module ckan.common has been deprecated since CKAN v2.10.0"

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/who-romania-ckan#24]
Getting ridiculously large numbers of warnings saying:

{noformat}Function is_flask_request() in module ckan.common has been deprecated since CKAN v2.10.0 and will be removed in a later release of ckan. All web requests are served by Flask"{noformat}

We need to fix this.

**Comment by mixmixmix** [comment]
This is I believe done by JB with this: https://github.com/fjelltopp/ckanext-who-romania/pull/19
