### ISSUE TITLE
Create Requirements Spradsheet

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/who-romania-ckan#32]

**Comment by ChasNelson1990** [comment]
AFRO requirements can be found here: [https://docs.google.com/spreadsheets/d/1jK5nig0Pa8CfPfHKvIC2H9j8ZTREO0Lghwy0CCV4_2s/edit?usp=sharing|https://docs.google.com/spreadsheets/d/1jK5nig0Pa8CfPfHKvIC2H9j8ZTREO0Lghwy0CCV4_2s/edit?usp=sharing|smart-link] 
Originally posted by jonathansberry on Jira.

**Comment by ChasNelson1990** [comment]
Cyber security requirements are available here: [https://drive.google.com/file/d/1-hJ0jJV6W57Mk-NLUThFYLwcWZMmoDG3/view?usp=drive_link|https://drive.google.com/file/d/1-hJ0jJV6W57Mk-NLUThFYLwcWZMmoDG3/view?usp=drive_link|smart-link] 
Originally posted by jonathansberry on Jira.

**Comment by ChasNelson1990** [comment]
I have copied over the AFRO requirements, updated them appropriately, and replaced the cybersecurity requirements with Cybersecurity requirements list for this specific project. It provides a starting place to direct future work. 
Originally posted by jonathansberry on Jira.

**Comment by mixmixmix** [comment]
This is duplicated of #55
