### ISSUE TITLE
Investigate upload of files to data hubs through kobotoolbox forms

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/who-romania-ckan#49]
Upload of files through kobotoolbox to data platform (Jonjo tested the form he created for the family doctors)

* Easy way for WHO team to see if everything got submitted
* good thing is that we can see in a spreadsheet what has been submitted
* kobo toolbox is a good start and maybe thats as far as we need?

**Comment by ChasNelson1990** [comment]
[~accountid:5cc1eb1b2f51be0e56a1bad8] This should be a task, somehow “Create issue” created “a story”. I see no option or menu where I can turn it to a task.
Originally posted by mixmixmix on Jira.

**Comment by mixmixmix** [comment]
This should be closed, we decided on kobotoolbox
