### ISSUE TITLE
investigate alternatives to MS Sway for sitreps

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/who-romania-ckan#50]
MS Sway is horrible in formatting - e.g. it displays column of text only partially on my computer, it forces pictures to be zoomed in etc. - and JJ struggles sometimes to make it work correctly.

Sylvia likes “the feel” of sway. Would be good to have sth else that is easy to use.

Data for sitrep is shared in bits and bobs.

**Comment by mixmixmix** [comment]
I looked into this a bit, and it seems that for now MS Sway is better than alternatives. The responsiblity for them is moving away from Jonjo, and a new person might have background in graphics/design to use more advanced tools. Unless the issues bounces back at us, it is done.
