### ISSUE TITLE
Create a ckanext-fjelltopp extension

### ISSUE THREAD

**Issue by ChasNelson1990** [fjelltopp/who-romania-ckan#91]
The idea is that generic features needed for many of our clients CKAN instances would be developed in a new extension ckanext-fjelltopp.  

Each separate feature could be switched off by a config param. 

This way we simplify maintenance of those many little features that are needed in all of our projects:

e.g. giftless upload, automatic username generation, and sysadmin user substitution.

**Comment by mixmixmix** [comment]
@ChasNelson1990 This issue should not be here. But this issue (or whatever it is a duplicate of), is in my opinion quite important.

**Comment by ChasNelson1990** [comment]
We have started this by first extracting theme in https://github.com/fjelltopp/ckanext-fjelltopp-theme

Other developments will be their own ckan-exts, e.g. https://github.com/fjelltopp/ckanext-file-uploader-js

We will then create a vanilla Fjelltopp-ckan that we host somewhere for demos and our own file storage.
